version: '3'

services:
  payload:
    image: ghcr.io/joshgermon/angela-and-josh-photography-cms/payload:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: production
      PAYLOAD_SECRET: 8c8bd8d29492741cf9a42f41

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
